# Generated by Django 4.1.7 on 2023-05-20 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_code', models.TextField()),
                ('accept', models.BooleanField(default=False)),
                ('id_inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.team')),
            ],
        ),
    ]
