# Generated by Django 4.1.7 on 2023-05-24 21:02

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_invite_team'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='task',
            managers=[
                ('func_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
