# Generated by Django 4.1.7 on 2023-05-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_task_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite_team',
            name='role',
            field=models.CharField(choices=[('1', 'admin'), ('2', 'developer'), ('3', 'manager'), ('4', 'QA'), ('5', 'architect'), ('6', 'SEO')], default=None, max_length=1, null=True),
        ),
    ]
