# Generated by Django 4.1.7 on 2023-04-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(default='./media/default_photo', upload_to='./media/'),
        ),
    ]
