# Generated by Django 4.1.7 on 2023-04-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(default='default_photo.png', upload_to='user_images/'),
        ),
    ]
